FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Відкриваємо порт Vite
EXPOSE 5173

# Запускаємо з прапором --host, щоб Docker міг прокинути порт
CMD ["npm", "run", "dev", "--", "--host"]